# Project information
site_name: Lambda Feedback Documentation
site_author: Pierre Tharreau, Louis Manestar
site_url: https://lambda-feedback.github.io/user-documentation/
site_description: >-
  Architecture, syntax and usage details for an online learning platform
  focused on providing rich feedback to the user.
repo_url: https://github.com/lambda-feedback/user-documentation
edit_uri: blob/main/docs/

# Project tree
nav:
  - Home:
      - "index.md"
      - Publications: "publications.md"
      - Opportunities: "opportunities.md"
      - Terminology: "terminology.md"
      - Releases:
          - Major releases: "releases/major_releases.md"
          - Detailed Releases: "releases/detailed_releases.md"
          - Previous releases:
              - 2023-24: "releases/relases_2023_24.md"
          - Status: "releases/status.md"

  - Students:
      - "student/index.md"
      - Getting Started: "student/getting_started_student.md"
      - Answering Questions: "student/answering_questions.md"
      - Response Areas: "student/response_areas.md"
      - Text Editing: "student/lexdown_student.md"
      - FAQ: "student/faq.md"

  - Teachers:
      - "teacher/index.md"
      - Guides:
          - Getting Started: "teacher/guides/gettingstarted.md"
          - Editing questions: "teacher/guides/content-sets-questions.md"
          - Exporting and importing questions: "teacher/guides/question-export-import.md"
          - Milkdown: "teacher/guides/lexdown.md"
          - Analytics: "teacher/guides/analytics.md"
          - Good practice: "teacher/guides/good-practice.md"
          - FAQ: "teacher/guides/faq.md"
          - Guidance:
              - Guidance Time Suggestion: "teacher/guides/guidance/guidance-time-suggestion.md"

      - Reference:
          - Access control: "teacher/reference/access_control.md"
          - Latex functionality: "teacher/reference/latex_functionality.md"
          - PDF generation: "teacher/reference/pdf_generation.md"
          - Response Areas:
              - "teacher/reference/response_area_components/index.md"
              - Text: "teacher/reference/response_area_components/Text.md"
              - Number: "teacher/reference/response_area_components/Number.md"
              - Boolean: "teacher/reference/response_area_components/Boolean.md"
              - NumericUnits: "teacher/reference/response_area_components/NumericUnits.md"
              - Expression: "teacher/reference/response_area_components/Expression.md"
              - MultipleChoice: "teacher/reference/response_area_components/MultipleChoice.md"
              - Matrix: "teacher/reference/response_area_components/Matrix.md"
              - Table: "teacher/reference/response_area_components/Table.md"
          - Evaluation Functions:
              - "teacher/reference/evaluation_functions/index.md"

  - Advanced:
      - "advanced/index.md"
      - Response Areas:
          - Overview: "advanced/response_areas/overview.md"
      - Evaluation Functions:
          - Quickstart Guide: "advanced/evaluation_functions/quickstart.md"
          - General Specification: "advanced/evaluation_functions/specification.md"
          - Feedback: "advanced/evaluation_functions/feedback.md"
          - Testing Functions Locally: "advanced/evaluation_functions/local.md"
          - Evaluation Function Utils: "advanced/evaluation_functions/module.md"
          - Deployed Functions:
              - "advanced/evaluation_functions/index.md"
          - Alternate Function Languages: "advanced/evaluation_functions/alternate_languages.md"
      - Chat functions:
          - Quickstart: "advanced/chat_functions/quickstart.md"
          - Testing Functions Locally: "advanced/chat_functions/local.md"

# Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: fontawesome/solid/pen-to-square
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    #- navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  # - meta
  - tables

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - macros
  - evaldocsloader:
      enabled: !ENV [ENABLE_EVALDOCS, true]
      functions_announce_endpoint: "https://prod-api.lambdafeedback.com/evaluation-functions/registered"
      api_key:
        !ENV [
          API_KEY,
          "WiOS1vMpQyTuGL06ZJxjG1eZd2P0SPvuVzHpr6zjkTIJ33U2t5O5NWaZboWBv8aV",
        ]
      dev_section: ["Advanced", "Evaluation Functions", "Deployed Functions"]
      user_section: ["Teachers", "Reference", "Evaluation Functions"]
      github_token: !ENV [GITHUB_TOKEN, ""]

# Extra variables, accessible within markdown pages
extra:
  urls:
    client: https://lambdafeedback.com
